language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
notifications:
  email: false

# Install packages
install:
  - pip install numpy 
  - pip install pandas 
  - pip install xarray
  - python setup.py install
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
