language: python
python:
  - "3.6"
notifications:
  email: false

# Install packages
install:
  - pip install numpy scipy netCDF4 pandas xarray dask
  - python setup.py install
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
