name: analogue
channels:
   - conda-forge
dependencies:
   - python=3.6
   - numpy
   - scipy
   - matplotlib
   - cartopy
   - netcdf4
   - xarray
   - pint
   - pytest>=2.4
   - pytest-cov
   - pytest-flake8
   - pytest-mpl
   - pytest-runner
   - flake8-builtins!=1.4.0
   - flake8-comprehensions
   - flake8-copyright
   - flake8-docstrings
   - flake8-import-order
   - flake8-mutable
   - flake8-pep3101
   - flake8-print
   - flake8-quotes
   - pep8-naming
   - doc8
